apiVersion: v1
kind: Secret
metadata:
  name: gmail-auth
  namespace: monitoring
type: Opaque
stringData:
  #  Helm va injecter le mot de passe ici lors du déploiement !
  password: {{ .Values.gmailPassword | quote }} 