apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  # On va chercher le nombre de réplicas dans values.yaml
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        #  On va chercher le nom de l'image dynamique
        image: {{ .Values.frontend.image }}
        ports:
        #  On va chercher le port dynamique
        - containerPort: {{ .Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}