---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: kubernetes-resources
      rules:
        - alert: ContainerHighMemory
          expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.9
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Le conteneur {{`{{ $labels.container }}`}} manque de RAM"
            description: "Le conteneur {{`{{ $labels.container }}`}} du pod {{`{{ $labels.namespace }}`}}/{{`{{ $labels.pod }}`}} utilise plus de 90% de sa mémoire allouée depuis 5 minutes."

        - alert: KubernetesPodCrashLoopBack
          expr: kube_pod_container_status_restarts_total > 5
          for: 0m
          labels:
            severity: critical
            namespace: monitoring
          annotations:
             description: "Pod {{`{{ $labels.pod }}`}} is crash looping\n  Value = {{`{{ $value }}`}}"
             summary: Kubernetes pod crash looping
          

