---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: aks-memory-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: kubernetes-resources
      rules:
        - alert: ContainerHighMemory
          expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.9
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Le conteneur {{ "{{ $labels.container }}" }} manque de RAM
            description: Le conteneur {{ "{{ $labels.container }}" }} du pod {{ "{{
              $labels.namespace }}" }}/{{ "{{ $labels.pod }}" }} utilise plus de
              90% de sa mémoire allouée depuis 5 minutes.
