apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: kubernetes-resources
      rules:
        #  1. Tes alertes (Ressources & Crash)
        - alert: ContainerHighMemory
          expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.9
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Le conteneur {{`{{ $labels.container }}`}} manque de RAM"
            description: "Le conteneur {{`{{ $labels.container }}`}} du pod {{`{{ $labels.namespace }}`}}/{{`{{ $labels.pod }}`}} utilise plus de 90% de sa mémoire allouée depuis 5 minutes."

        - alert: KubernetesPodCrashLoopBack
          expr: kube_pod_container_status_restarts_total > 5
          for: 0m
          labels:
            severity: critical
            namespace: monitoring
          annotations:
             description: "Pod {{`{{ $labels.pod }}`}} is crash looping\n  Value = {{`{{ $value }}`}}"
             summary: Kubernetes pod crash looping back

        #  2. Alertes Infrastructure (Niveau Cluster)
        - alert: NodeNotReady
          expr: kube_node_status_condition{condition="Ready",status="true"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Le noeud {{`{{ $labels.node }}`}} est DOWN"
            description: "Un serveur de ton cluster AKS ne répond plus depuis 5 minutes. Risque d'indisponibilité."

        - alert: TargetDown
          # Vérifie si le radar Prometheus arrive à joindre tes conteneurs
          expr: up == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Cible de monitoring injoignable"
            description: "Prometheus n'arrive plus à lire les métriques de {{`{{ $labels.job }}`}}."

        #  3. Alertes Applicatives (API FastAPI)
        - alert: HighHttpErrorRate
          # Déclenche si le ratio d'erreurs 5xx dépasse 10% sur la dernière minute
          expr: sum(rate(http_requests_total{status=~"5.."}[1m])) / sum(rate(http_requests_total[1m])) > 0.10
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pic d'erreurs 500 sur l'API"
            description: "Plus de 10% des requêtes ont échoué récemment. Ton application renvoie des erreurs aux utilisateurs !"

        - alert: ApiHighLatency
          # Déclenche si le temps de réponse moyen dépasse 2 secondes
          expr: rate(http_request_duration_seconds_sum[2m]) / rate(http_request_duration_seconds_count[2m]) > 2
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "L'API est très lente"
            description: "Le temps de réponse moyen dépasse 2 secondes depuis 2 minutes."