name: Build and deploy to AKS

on:
  push:
    branches: 
      - main
    paths:
      - 'app/**'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: "acrmahjoubidev2026"
  CLUSTER_NAME: "aks-dev-frc-001"
  RG_NAME: "rg-aks-dev-frc"

jobs:
  # ---------------------------------------------------
  #  JOB 1 : Construction des images en parallèle
  # ---------------------------------------------------
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend] 
    
    steps:
      - name:  Checkout du code
        uses: actions/checkout@v4

      - name:  Connexion à Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name:  Connexion à l'ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name:  Build & Push Docker (${{ matrix.service }})
        run: |
          TAG=${{ github.sha }}
          FULL_IMAGE="${{ env.ACR_NAME }}.azurecr.io/${{ matrix.service }}:$TAG"
          
          echo "Construction de l'image : $FULL_IMAGE"
          cd app/${{ matrix.service }}
          docker build -t $FULL_IMAGE .
          docker push $FULL_IMAGE

  # ---------------------------------------------------
  #  JOB 2 : Déploiement sur le cluster K8s
  # ---------------------------------------------------
  deploy-to-aks:
    needs: build-images
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout du code
        uses: actions/checkout@v4

      - name:  Connexion à Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name:  Récupérer le contexte AKS
        uses: azure/aks-set-context@v3
        with: 
          resource-group: ${{ env.RG_NAME }}
          cluster-name: ${{ env.CLUSTER_NAME }} 

      - name:  Déploiement K8s (Microservices)
        run: |
          TAG=${{ github.sha }}
          
          # On prépare les URLs exactes de nos deux images
          FRONTEND_IMAGE="${{ env.ACR_NAME }}.azurecr.io/frontend:$TAG"
          BACKEND_IMAGE="${{ env.ACR_NAME }}.azurecr.io/backend:$TAG"

          # On remplace les mots magiques dans nos fichiers YAML avec sed
          sed -i "s|__FRONTEND_IMAGE__|$FRONTEND_IMAGE|g" app/deploy/frontend.yaml
          sed -i "s|__BACKEND_IMAGE__|$BACKEND_IMAGE|g" app/deploy/backend.yaml

          # On déploie les 3 fichiers (Redis, Backend, Frontend) d'un coup !
          kubectl apply -f app/deploy/