
name:  Déploiement Infrastructure (Terraform)

on:
    # MAGIE : Ajoute un bouton "Run workflow" sur GitHub pour le lancer à la main le matin 
    workflow_dispatch:
    push:
        paths:
            # Se lance tout seul SI on modifie le code Terraform
          - 'infra/**'

permissions:
  id-token: write
  contents: read


# Variables d'environnement spéciales pour que Terraform utilise ton OIDC sans mot de passe
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true


jobs:
    terraform-deploy:
      runs-on: ubuntu-latest
        # On dit au robot de toujours se placer dans ce dossier avant de taper ses commandes
      defaults:
        run:
          working-directory: infra/envs/dev

      steps:
        - name: checkout du code
          uses: actions/checkout@v4
        
        - name: Connexion à Azure (OIDC)
          uses: azure/login@v2
          with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Installation de Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Terraform Init
          run: terraform init

        - name: Terraform Plan
          run: terraform plan

        - name: Terraform Apply
          run: terraform apply -auto-approve